// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAzBhuJYFonBBaIUuvhMUG98B5KLl5lX0',
    appId: '1:819370147216:web:28d82df14f185535bec715',
    messagingSenderId: '819370147216',
    projectId: 'weather-3eee6',
    authDomain: 'weather-3eee6.firebaseapp.com',
    storageBucket: 'weather-3eee6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSq8Dz3qhHcV0n09IuImY3Zxog6gmh5qU',
    appId: '1:819370147216:android:b3d2b49f743a2499bec715',
    messagingSenderId: '819370147216',
    projectId: 'weather-3eee6',
    storageBucket: 'weather-3eee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6bB4ne1lNcJnr74Gt-ZoyIAz82IUQDYw',
    appId: '1:819370147216:ios:fd5bc93fa176ca86bec715',
    messagingSenderId: '819370147216',
    projectId: 'weather-3eee6',
    storageBucket: 'weather-3eee6.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6bB4ne1lNcJnr74Gt-ZoyIAz82IUQDYw',
    appId: '1:819370147216:ios:fd5bc93fa176ca86bec715',
    messagingSenderId: '819370147216',
    projectId: 'weather-3eee6',
    storageBucket: 'weather-3eee6.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAzBhuJYFonBBaIUuvhMUG98B5KLl5lX0',
    appId: '1:819370147216:web:6b8a32d2ec2923e8bec715',
    messagingSenderId: '819370147216',
    projectId: 'weather-3eee6',
    authDomain: 'weather-3eee6.firebaseapp.com',
    storageBucket: 'weather-3eee6.firebasestorage.app',
  );
}
